In [ ]:
%tensorflow_version 2.x

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
# Get the current working directory
cwd = os.getcwd()

# Print the current working directory
print("Current working directory: {}".format(cwd))

# Change the working directory
os.chdir('/content/drive/MyDrive/ConsDeepSignaling')

# Print the current working directory
print("Current working directory: {}".format(os.getcwd()))

Current working directory: /content
Current working directory: /content/drive/MyDrive/ConsDeepSignaling


In [3]:
# 필요한한 라이브러리리 설치
!pip install innvestigate simplejson

     |████████████████████████████████| 100 kB 3.4 MB/s 
     |████████████████████████████████| 130 kB 32.4 MB/s 
     |████████████████████████████████| 312 kB 39.7 MB/s 
     |████████████████████████████████| 50 kB 6.0 MB/s 
  Attempting uninstall: keras
    Found existing installation: keras 2.7.0
    Uninstalling keras-2.7.0:
      Successfully uninstalled keras-2.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.7.0 requires keras<2.8,>=2.7.0rc0, but you have keras 2.2.4 which is incompatible.


In [4]:
import os
import pickle
import innvestigate
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from gen_matrix import GenMatrix
from parse_file import ParseFile
from load_data import LoadData
from analysis import Analyse
from keras_rand_nn import RandNN, RunRandNN

Using TensorFlow backend.


In [5]:
print('READING DIMS...')
dir_opt = '/datainfo'
train_input_df, input_num, num_feature, rna_df, cpnum_df, num_gene, num_pathway = LoadData(dir_opt).pre_load_train()

matrixA = GenMatrix.feature_gene_matrix(num_feature, num_gene)
matrixB = GenMatrix.gene_pathway_matrix()
print('-----MATRIX A - FEATURES OF GENE SHAPE-----')
print(matrixA.shape)
print('-----MATRIX B - GENE PATHWAY SHAPE-----')
print(matrixB)

READING DIMS...
-----MATRIX A - FEATURES OF GENE SHAPE-----
(2787, 929)
-----MATRIX B - GENE PATHWAY SHAPE-----
[[0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
matrixA

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [7]:
# gene_pathway_matrix.npy
matrixB

array([[0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
import tensorflow.keras as keras
from main import *
# import tensorflow.keras as keras

print('RUNING DEEP NERUAL NETWORK...')

# BUILD NEURAL NETWORK
print('BUILDING CUSTOMED NERUAL NETWORK...')
layer0 = num_pathway
layer1 = 256
layer2 = 128
layer3 = 32

epoch = 5
batch_size = 256
verbose = 0
learning_rate = 0.001
end_epoch = 5

input_model, gene_model, pathway_model, model = build_rand_nn(matrixA, matrixB, num_gene, num_pathway, layer1, layer2, layer3)

model, history, path = run_rand_nn(model, dir_opt, matrixA, matrixB, 
                                   input_num, epoch, batch_size, verbose, 
                                   learning_rate, end_epoch)

RUNING DEEP NERUAL NETWORK...
BUILDING CUSTOMED NERUAL NETWORK...


AttributeError: ignored

In [ ]:
auto_test_rand_nn(model, dir_opt, verbose, path)

In [ ]:
tf.keras.utils.plot_model(model, show_shapes=True)

In [ ]:
tf.keras.utils.plot_model(gene_model, show_shapes=True)

In [ ]:
tf.keras.utils.plot_model(pathway_model, show_shapes=True)

In [ ]:
tf.keras.utils.plot_model(input_model, show_shapes=True)